### ISSUE TITLE
build fails on aur_sync

### ISSUE THREAD

**Issue by joshuacox** [xeladejo/aurci#1]
```
:: Starting full system upgrade...
 there is nothing to do
+ shopt -u nullglob
+ ((  1  ))
+ aur sync -d aurci -n dropbox
mkdir: cannot create directory ‘/run/user/1000’: Permission denied
The command "docker exec aurci bash build.sh" exited with 1.
```

**Comment by xeladejo** [comment]
Issue of https://github.com/AladW/aurutils/issues/775 introduced in version 3.0.1 (https://github.com/AladW/aurutils/commit/5341c059736d3eff59daea5cb52b7d35c98d0824) and fixed in version 3.0.3 (https://github.com/AladW/aurutils/commit/45f6ce678da4eae2eebf1a3afa88d0b7d68d81fd).

With `aurutils-3.0.3` builds works correctly:  https://travis-ci.com/github/xeladejo/aurci/builds/198542271
